version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/build"
    reviewers:
      - UCBoulder/oit-sepe
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ansible"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/spec"
    reviewers:
      - UCBoulder/oit-sepe
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ansible"
        update-types: ["version-update:semver-major"]
