---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: community.hashi_vault
  - name: community.vmware
  - name: vmware.vmware_rest
  - name: crowdstrike.falcon
