---
collections:
  - name: awx.awx
# Out until https://github.com/ansible-collections/azure/pull/584 is merged
#- name: azure.azcollection
  - name: https://github.com/erinn/azure/
    type: git
    version: patch-1
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
# SEPE additions (should speed up repo sync if installed here)
  - name: community.general
  - name: community.hashi_vault
  - name: community.vmware
  - name: vmware.vmware_rest
