name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          # Use builtin python version: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#python
          python-version: "3.9.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Downcase repo path
        run: |
          echo "REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=${{ env.REPO }}/awx-ee:${{ github.event.release.tag_name }}
          docker tag ${{ env.REPO }}/awx-ee:${{ github.event.release.tag_name }} ${{ env.REPO }}/awx-ee:latest
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.REPO }}/awx-ee:${{ github.event.release.tag_name }}
          docker push ${{ env.REPO }}/awx-ee:latest
